respawn_world: world
tag_ticks: 600
summon_damage_ticks: 20
logout_imprison: true
prison_world: world_the_end
prison_motd:
   - You are trapped in this bleak and endless world
   - by a prison pearl.
   - Type /pplocate to locate your pearl.
