respawn_world: world
damage_min: 3
damage_ticks: 600
summon_damage_radius: 20
summon_damage_ticks: 20
summon_damage_amt: 2
prison_world: world_the_end
prison_motd:
   - You are trapped in this bleak and endless world
   - by a prison pearl.
   - Type /pplocate to locate your pearl.
