name: PrisonPearl
main: com.untamedears.PrisonPearl.PrisonPearlPlugin
version: 1.1.3

commands:
   pplocate:
      description: Locates your prison pearl
      usage: /<command>
      aliases: ppl
  
   pplocateany:
      description: Locates any prison pearl in the world
      usage: /<command> player
      permission: prisonpearl.locateany
   
   ppfree:
      description: Frees a prison pearl
      usage: /<command> [player]
      aliases: ppf
      
   ppfreeany:
      description: Frees any prison pearl in the world
      usage: /<command> player
      permission: prisonpearl.freeany
      
   ppsummon:
      description: Summons a player from their prison pearl
      usage: /ppsummon [player]
      aliases: pps
      
   ppreturn:
      description: Returns a summoned player back to their prison pearl
      usage: /ppbanish [player]
      aliases: ppr
      
   ppkill:
      description: Instantly kills a summoned player, sending them back to their prison pearl
      usage: /ppkill [player]
      aliases: ppk
      
   ppsave:
      description: Saves all prisonpearl related data to disk
      usage: /ppsave
      permission: prisonpearl.save
      
   ppimprisonany:
      description: Imprisons any player in the world
      usage: /ppimprisonany player
      permission: prisonpearl.imprisonany
      
   ppbroadcast:
      description: Broadcast your pplocate commands to another player
      usage: /ppbroadcast player
      
   ppconfirm:
      description: Confirm reception of pplocate commands from a player
      usage: /ppconfirm [player]
      
   ppsilence:
      description: Silence reception of pplocate commands from player
      usage: /ppsilence player
      
permissions:
   prisonpearl.*:
      description: Gives full access to PrisonPearl commands
      default: op
      children:
         prisonpearl.locateany: true
         prisonpearl.freeany: true
         prisonpearl.imprisonany: true
         prisonpearl.save: true

   prisonpearl.locateany:
      description: Allows user to use pplocateany to locate prison pearls other than his own
      
   prisonpearl.freeany:
      description: Allows user to use ppfreeany to free prison pearls he does not possess
      
   prisonpearl.save:
      description: Allows user to use ppsave command
   
      