name: PrisonPearl
main: com.untamedears.PrisonPearl.PrisonPearlPlugin
version: 0.2

commands:
   pplocate:
      description: Locates your prison pearl
      usage: /<command>
  
   pplocateany:
      description: Locates any prison pearl in the world
      usage: /<command> player
      permission: prisonpearl.locateany
   
   ppfree:
      description: Frees a prison pearl
      usage: /<command> [player]
      
   ppfreeany:
      description: Frees any prison pearl in the world
      usage: /<command> player
      permission: prisonpearl.free
      
   ppsummon:
      description: Summons a player from their prison pearl
      usage: /ppsummon [player]
      
   ppreturn:
      description: Returns a summoned player back to their prison pearl
      usage: /ppbanish [player]
      
   ppkill:
      description: Instantly kills a summoned player, sending them back to their prison pearl
      usage: /ppkill [player]
      
permissions:
   prisonpearl.*:
      description: Gives full access to PrisonPearl commands
      default: op
      children:
         prisonpearl.locateany: true
         prisonpearl.freeany: true

   prisonpearl.locateany:
      description: Allows user to locate prison pearls other than his own
      
   prisonpearl.freeany:
      description: Allows user to free prison pearls he does not possess
      